// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoC.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ThirdMessage struct {
	Imported             *LastMessage `protobuf:"bytes,1,opt,name=imported,proto3" json:"imported,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ThirdMessage) Reset()         { *m = ThirdMessage{} }
func (m *ThirdMessage) String() string { return proto.CompactTextString(m) }
func (*ThirdMessage) ProtoMessage()    {}
func (*ThirdMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_protoC_8f13b156dc6f2866, []int{0}
}
func (m *ThirdMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThirdMessage.Unmarshal(m, b)
}
func (m *ThirdMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThirdMessage.Marshal(b, m, deterministic)
}
func (dst *ThirdMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThirdMessage.Merge(dst, src)
}
func (m *ThirdMessage) XXX_Size() int {
	return xxx_messageInfo_ThirdMessage.Size(m)
}
func (m *ThirdMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ThirdMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ThirdMessage proto.InternalMessageInfo

func (m *ThirdMessage) GetImported() *LastMessage {
	if m != nil {
		return m.Imported
	}
	return nil
}

func init() {
	proto.RegisterType((*ThirdMessage)(nil), "protos.ThirdMessage")
}

func init() { proto.RegisterFile("protoC.proto", fileDescriptor_protoC_8f13b156dc6f2866) }

var fileDescriptor_protoC_8f13b156dc6f2866 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x77, 0xd6, 0x03, 0x53, 0x42, 0x6c, 0x60, 0xaa, 0x58, 0x0a, 0x22, 0xea, 0x02, 0x11, 0x55,
	0xb2, 0xe7, 0xe2, 0x09, 0xc9, 0xc8, 0x2c, 0x4a, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15,
	0xd2, 0xe7, 0xe2, 0xc8, 0xcc, 0x2d, 0xc8, 0x2f, 0x2a, 0x49, 0x4d, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x36, 0x12, 0x86, 0xa8, 0x2c, 0xd6, 0xf3, 0x49, 0x2c, 0x2e, 0x81, 0x2a, 0x0b, 0x82, 0x2b,
	0x4a, 0x82, 0x18, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x25, 0x99, 0x8f, 0xa3, 0x6d, 0x00,
	0x00, 0x00,
}
