// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoE.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageE struct {
	ENumber              int32    `protobuf:"varint,1,opt,name=eNumber,proto3" json:"eNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageE) Reset()         { *m = MessageE{} }
func (m *MessageE) String() string { return proto.CompactTextString(m) }
func (*MessageE) ProtoMessage()    {}
func (*MessageE) Descriptor() ([]byte, []int) {
	return fileDescriptor_protoE_1be76dcac2c5bacf, []int{0}
}
func (m *MessageE) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageE.Unmarshal(m, b)
}
func (m *MessageE) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageE.Marshal(b, m, deterministic)
}
func (dst *MessageE) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageE.Merge(dst, src)
}
func (m *MessageE) XXX_Size() int {
	return xxx_messageInfo_MessageE.Size(m)
}
func (m *MessageE) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageE.DiscardUnknown(m)
}

var xxx_messageInfo_MessageE proto.InternalMessageInfo

func (m *MessageE) GetENumber() int32 {
	if m != nil {
		return m.ENumber
	}
	return 0
}

func init() {
	proto.RegisterType((*MessageE)(nil), "protos.MessageE")
}

func init() { proto.RegisterFile("protoE.proto", fileDescriptor_protoE_1be76dcac2c5bacf) }

var fileDescriptor_protoE_1be76dcac2c5bacf = []byte{
	// 75 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x77, 0xd5, 0x03, 0x53, 0x42, 0x6c, 0x60, 0xaa, 0x58, 0x49, 0x85, 0x8b, 0xc3, 0x37, 0xb5,
	0xb8, 0x38, 0x31, 0x3d, 0xd5, 0x55, 0x48, 0x82, 0x8b, 0x3d, 0xd5, 0xaf, 0x34, 0x37, 0x29, 0xb5,
	0x48, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x08, 0xc6, 0x4d, 0x82, 0xa8, 0x36, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xc5, 0xe3, 0x7b, 0x44, 0x44, 0x00, 0x00, 0x00,
}
