// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoA.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ImportedMessage struct {
	ImportedMessage      string        `protobuf:"bytes,1,opt,name=ImportedMessage,proto3" json:"ImportedMessage,omitempty"`
	Num                  *ThirdMessage `protobuf:"bytes,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ImportedMessage) Reset()         { *m = ImportedMessage{} }
func (m *ImportedMessage) String() string { return proto.CompactTextString(m) }
func (*ImportedMessage) ProtoMessage()    {}
func (*ImportedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_protoA_b269ed5a6b471d98, []int{0}
}
func (m *ImportedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportedMessage.Unmarshal(m, b)
}
func (m *ImportedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportedMessage.Marshal(b, m, deterministic)
}
func (dst *ImportedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportedMessage.Merge(dst, src)
}
func (m *ImportedMessage) XXX_Size() int {
	return xxx_messageInfo_ImportedMessage.Size(m)
}
func (m *ImportedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ImportedMessage proto.InternalMessageInfo

func (m *ImportedMessage) GetImportedMessage() string {
	if m != nil {
		return m.ImportedMessage
	}
	return ""
}

func (m *ImportedMessage) GetNum() *ThirdMessage {
	if m != nil {
		return m.Num
	}
	return nil
}

func init() {
	proto.RegisterType((*ImportedMessage)(nil), "protos.ImportedMessage")
}

func init() { proto.RegisterFile("protoA.proto", fileDescriptor_protoA_b269ed5a6b471d98) }

var fileDescriptor_protoA_b269ed5a6b471d98 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x77, 0xd4, 0x03, 0x53, 0x42, 0x6c, 0x60, 0xaa, 0x58, 0x0a, 0x22, 0xea, 0x0c, 0x11, 0x55,
	0x4a, 0xe6, 0xe2, 0xf7, 0xcc, 0x2d, 0xc8, 0x2f, 0x2a, 0x49, 0x4d, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x15, 0xd2, 0xc0, 0x10, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xc2, 0x50, 0xa9,
	0xc6, 0xc5, 0x9c, 0x57, 0x9a, 0x2b, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x6d, 0x24, 0x02, 0x31, 0xb1,
	0x58, 0x2f, 0x24, 0x23, 0xb3, 0x08, 0xa6, 0x24, 0x08, 0xa4, 0x20, 0x09, 0x62, 0xb5, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x7c, 0x1f, 0xab, 0xcc, 0x91, 0x00, 0x00, 0x00,
}
