// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcans.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// RPCRes is the rpc response
type RPCRes struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RPCRes) Reset()         { *m = RPCRes{} }
func (m *RPCRes) String() string { return proto.CompactTextString(m) }
func (*RPCRes) ProtoMessage()    {}
func (*RPCRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpcans_70660cc77ebfc0b6, []int{0}
}
func (m *RPCRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCRes.Unmarshal(m, b)
}
func (m *RPCRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCRes.Marshal(b, m, deterministic)
}
func (dst *RPCRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCRes.Merge(dst, src)
}
func (m *RPCRes) XXX_Size() int {
	return xxx_messageInfo_RPCRes.Size(m)
}
func (m *RPCRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCRes.DiscardUnknown(m)
}

var xxx_messageInfo_RPCRes proto.InternalMessageInfo

func (m *RPCRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*RPCRes)(nil), "protos.RPCRes")
}

func init() { proto.RegisterFile("rpcans.proto", fileDescriptor_rpcans_70660cc77ebfc0b6) }

var fileDescriptor_rpcans_70660cc77ebfc0b6 = []byte{
	// 72 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2a, 0x48, 0x4e,
	0xcc, 0x2b, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x52, 0x5c,
	0x6c, 0x41, 0x01, 0xce, 0x41, 0xa9, 0xc5, 0x42, 0x02, 0x5c, 0xcc, 0xbe, 0xc5, 0xe9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0x66, 0x12, 0x44, 0x8d, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x5d, 0x7f, 0xed, 0x91, 0x3a, 0x00, 0x00, 0x00,
}
